FROM docker.io/redhat/ubi9:latest

WORKDIR /tests/

# RHSM
ADD ./tests/container/rhsm-enable-and-install-packages.sh .
RUN set -x \
    && chmod +x ./rhsm-enable-and-install-packages.sh \
    && ./rhsm-enable-and-install-packages.sh

# Main Ansible collection and playbook
ADD ./tests/playbook-* ./
ADD ./tests/container/inventory ./
ADD ./tests/container/ansible.cfg ./
ADD ./ ~/.ansible/collections/ansible_collections/thenets/osbuild/

# # Copy role to /usr/share/ansible/roles
# ADD ./ /usr/share/ansible/roles/osbuild-rhsm

# RUN set -ex \
#     && ansible-playbook -i inventory playbook-setup-host.yml
