---

- name: "include: for each in rhsm_repos, _each_rhsm_repo_setup.yml"
  ansible.builtin.include_tasks:
    file: _each_rhsm_repo_setup.yml
  loop: "{{ rhsm_repos }}"
  loop_control:
    loop_var: rhsm_repo

