FROM docker.io/redhat/ubi9:latest

WORKDIR /tests/

# RHSM
ADD ./tests/rhsm-enable-and-install-packages.sh .
RUN set -x \
    && chmod +x ./rhsm-enable-and-install-packages.sh \
    && ./rhsm-enable-and-install-packages.sh

ADD ./tests/playbook-* ./
ADD ./tests/inventory ./

# # Copy role to /usr/share/ansible/roles
# ADD ./ /usr/share/ansible/roles/osbuild-rhsm

# RUN set -ex \
#     && ansible-playbook -i inventory playbook-setup-host.yml
