---

- name: Assert variables are defined
  ansible.builtin.assert:
    that:
      - azure_storage_account_name is defined
      - azure_storage_account_access_key is defined
      - azure_storage_container_name is defined

# ------------
- name: "[block] setup"
  block:
    - name: Create profile.toml
      ansible.builtin.template:
        src: profile_azure.j2
        dest: "{{ composer_osbuild_workdir }}/profile.toml"
        mode: '0644'

    - name: Append azure packages to _packages_list
      vars:
        # WALinuxAgent: Azure's agent
        _azure_packages_list: ["WALinuxAgent"]
      ansible.builtin.set_fact:
        _packages_list: "{{ _packages_list + _azure_packages_list }}"

    - name: Create the osbuild blueprint
      when: composer_run_step_create_blueprint
      ansible.builtin.import_tasks: build-setup-blueprint.yml


# ------------
- name: "[block] main build step"
  block:
    - name: "Create a new build (timeout {{ composer_build_timeout_seconds }} seconds)"
      vars:
        _timestamp: "{{ lookup('pipe', 'date +%s') }}"
      ansible.builtin.command:
        cmd: "composer-cli compose start --timeout {{ composer_build_timeout_seconds }} {{ composer_build_name }} vhd {{ composer_build_name }}-{{ _timestamp }} {{ composer_osbuild_workdir }}/profile.toml"
      changed_when: result_create_build.rc == 0
      failed_when: result_create_build.rc == 1
      register: result_create_build

    - name: Debug build
      ansible.builtin.debug:
        msg: "{{ result_create_build.stdout_lines }}"

    # Loop: Wait for build to finish
    - name: "block: Wait for build to finish"
      block:
        - name: Set _compose_build_uuid
          ansible.builtin.set_fact:
            _compose_build_uuid: "{{ result_create_build.stdout_lines[0].split(' ')[1] }}"

        # DEBUG
        - debug:
            msg:
              - "_compose_build_uuid: {{ _compose_build_uuid }}"

        - name: "Check if build is finished : {{ _compose_build_uuid }} (timeout {{ composer_build_timeout_seconds }} seconds)"
          vars:
            time_seconds: "{{ composer_build_timeout_seconds }}"
          ansible.builtin.script:
            cmd: "{{ role_path }}/files/wait_until_build_is_finished.py {{ _compose_build_uuid }} {{ time_seconds }}"
            executable: python3
