---

# Check vars exist:
# gcp_bucket
# gcp_region
# gcp_object
# gcp_credentials_json_file_path
- name: Assert variables are defined
  ansible.builtin.assert:
    that:
      - gcp_bucket is defined
      - gcp_region is defined
      - gcp_object is defined
      - gcp_credentials_json_file_path is defined

# TODO fix this
#
# - name: Check if file exists
#   ansible.builtin.stat:
#     path: "{{ gcp_credentials_json_file_path }}"
#   register: gcp_credentials_json_file_path_stat
#   failed_when: false

- name: Encode credentials file
  ansible.builtin.set_fact:
    gcp_credentials_json_base64: "{{ lookup('file', gcp_credentials_json_file_path) | b64encode }}"


- name: Create config_gcp.toml file
  ansible.builtin.template:
    src: config_gcp.j2
    dest: "{{ composer_osbuild_workdir }}/config_gcp.toml"
    mode: '0644'
