---

- name: "Assert that the '_compose_build_id' variable is defined"
  assert:
    that:
      - _compose_build_id is defined
    fail_msg: "The '_compose_build_id' variable is not defined. Please make sure you defined it during the main build process."

# ------------
- name: "[block] Create the debug bundle"
  vars:
    _debug_bundle_dir_remote: "{{ composer_osbuild_workdir }}/{{ _build_name }}"
    _debug_bundle_dir_local: "{{ composer_local_output_dir }}/{{ _build_name }}"
  block:
    - name: "Create the debug bundle directory"
      ansible.builtin.file:
        path: "{{ _debug_bundle_dir_remote }}"
        state: directory
        mode: '0755'

    - name: "Extract 'composer-cli' metadata file"
      ansible.builtin.shell:
        chdir: "{{ _debug_bundle_dir_remote }}"
        cmd: |
          composer-cli compose metadata {{ _compose_build_id }}

    - name: "Copy the blueprint to the debug bundle"
      ansible.builtin.shell:
        chdir: "{{ _debug_bundle_dir_remote }}"
        cmd: |
          cp {{ composer_osbuild_workdir }}/blueprint.toml ./blueprint.toml

    - name: "Create local destionation directory"
      connection: local
      ansible.builtin.file:
        path: "{{ _debug_bundle_dir_local }}"
        state: directory
        mode: '0755'

    - name: "Download the build bundle to the local machine"
      ansible.builtin.synchronize:
        mode: pull
        src: "{{ _debug_bundle_dir_remote }}"
        path: "{{ _debug_bundle_dir_local }}"
        delete: false
