---

- name: Assert variables are defined
  ansible.builtin.assert:
    that:
      - gcp_bucket is defined
      - gcp_region is defined
      - gcp_object is defined
      - gcp_credentials_json_file_path is defined

- name: Check if file exists
  connection: local
  ansible.builtin.stat:
    path: "{{ gcp_credentials_json_file_path }}"
  register: gcp_credentials_json_file_path_stat

- name: Fail if GCP credentials file does not exist
  ansible.builtin.fail:
    msg: "File '{{ gcp_credentials_json_file_path }}' does not exist"
  when: gcp_credentials_json_file_path_stat.stat.exists == false

- name: Encode credentials file
  ansible.builtin.set_fact:
    gcp_credentials_json_base64: "{{ lookup('file', gcp_credentials_json_file_path) | b64encode }}"

- name: Create profile.toml
  ansible.builtin.template:
    src: profile_gcp.j2
    dest: "{{ composer_osbuild_workdir }}/profile.toml"
    mode: '0644'

- name: Append GCP packages to _packages_list
  vars:
    _gcp_packages_list: []
  ansible.builtin.set_fact:
    _packages_list: "{{ _packages_list + _gcp_packages_list }}"
