---

# Input validation
# ----------------

# TODO: this may be a bad idea. It is not that uncommon to have multiple private registries
#       to be authenticated during a build process. An `authfile.json` would be more flexible
#       on this regard.
- name: Assert that required variables are set
  ansible.builtin.assert:
    that:
      - podman_username is defined
      - podman_password is defined

# Subscription Manager
# --------------------
- name: "[include task] ./tasks/enable_rhsm_repos.yml"
  when: composer_run_step_enable_rhsm_repos
  include_tasks: ./tasks/enable_rhsm_repos.yml
  tags:
    - enable_repos

# Setup osbuild config files and repos
# ------------------------------------
- name: "[include task] ./tasks/setup_osbuild_and_repos.yml"
  when: composer_run_step_setup_osbuild
  include_tasks: ./tasks/setup_osbuild_and_repos.yml
  tags:
    - setup_osbuild

# Blueprint and image creation
# ----------------------------
- name: Create the osbuild blueprint
  when: composer_run_step_create_blueprint
  ansible.builtin.import_tasks: blueprint.yml

- name: Setup Azure's credentials
  ansible.builtin.import_tasks: azure.yml

- name: Run the composer (build the image)
  ansible.builtin.import_tasks: build.yml
