---
- name: Assert that required variables are set
  ansible.builtin.assert:
    that:
      - podman_username is defined
      - podman_password is defined

- name: Setup osbuild and repos
  ansible.builtin.import_tasks: setup_osbuild_and_repos.yml

- name: Create osbuild blueprint
  when: composer_run_step_create_blueprint
  ansible.builtin.import_tasks: blueprint.yml

- name: Create azure.toml file
  ansible.builtin.import_tasks: azure.yml

- name: Build image
  ansible.builtin.import_tasks: build.yml
