---
- name: Assert that required variables are set
  ansible.builtin.assert:
    that:
      - podman_username is defined
      - podman_password is defined

- name: Build Image
  ansible.builtin.import_tasks: setup_osbuild_and_repos.yml
