# All RHSM repos required by the "composer-cli" blueprint must be enabled
# on the host machine.

---

- name: Enable Ansible Automation Repository repository
  community.general.rhsm_repository:
    name:
      - "ansible-automation-platform-{{ aap_version }}-for-rhel-{{ rhel_version }}-x86_64-rpms"

