---
- name: Enable Ansible Automation Repository repository
  community.general.rhsm_repository:
    name:
      - "ansible-automation-platform-{{ host_setup_aap_version }}-for-rhel-{{ host_setup_rhel_version }}-x86_64-rpms"
  tags:
    - enable_repos
