---
- name: Build Azure VM image
  hosts: all
  gather_facts: true
  become: true
  tasks:
    - name: Assert Azure variables are set
      ansible.builtin.assert:
        that:
          - azure_storage_account_name is defined
          - azure_storage_account_access_key is defined
          - azure_storage_container_name is defined
        fail_msg: "Azure variables are not set"

    - name: Import composer role
      vars:
        composer_platform: azure
      ansible.builtin.import_role:
        name: composer
